export const knownProductNames = [
  "TDH 数据工程版",
  "TDH 数据湖版",
  "TDH 集市版",
  "TDH 湖仓版",
  "TDH 湖仓集一体版",
  "TDH",
  "ArgoDB AP",
  "ArgoDB TP",
  "ArgoDB HTAP",
  "ArgoDB",
  "TDS-SUITE-T",
  "TDS-SUITE-D",
  "TDS-SUITE-R",
  "TDS-SUITE-E",
  "TDS",
  "Astro",
  "TDC Platform Service",
  "TDC Data Services",
  "TDC AI服务版",
  "TDC",
  "LLMOps",
  "TKH",
  "无涯·问数",
  "无涯·问知",
  "Scope",
  "Slipstream",
  "EventStore",
  "CognitiveDB",
  "TimeLyre",
] as const;
